// Shared navigation configuration for both sidebar and top navigation

export const componentsNavigation = [
  { title: "Accordion", url: "/components/accordion" },
  { title: "Alert", url: "/components/alert" },
  { title: "Alert Dialog", url: "/components/alert-dialog" },
  { title: "Avatar", url: "/components/avatar" },
  { title: "Badge", url: "/components/badge" },
  { title: "Breadcrumb", url: "/components/breadcrumb" },
  { title: "Button", url: "/components/button" },
  { title: "Button Group", url: "/components/button-group" },
  { title: "Calendar", url: "/components/calendar" },
  { title: "Card", url: "/components/card" },
  { title: "Carousel", url: "/components/carousel" },
  { title: "Chart", url: "/components/chart" },
  { title: "Checkbox", url: "/components/checkbox" },
  { title: "Collapsible", url: "/components/collapsible" },
  { title: "Combobox", url: "/components/combobox" },
  { title: "Command", url: "/components/command" },
  { title: "Date Picker", url: "/components/date-picker" },
  { title: "Context Menu", url: "/components/context-menu" },
  { title: "Dialog", url: "/components/dialog" },
  { title: "Drawer", url: "/components/drawer" },
  { title: "Dropdown Menu", url: "/components/dropdown-menu" },
  { title: "Empty", url: "/components/empty" },
  { title: "Field", url: "/components/field" },
  { title: "Hover Card", url: "/components/hover-card" },
  { title: "Input", url: "/components/input" },
  { title: "Input Group", url: "/components/input-group" },
  { title: "Item", url: "/components/item" },
  { title: "Kbd", url: "/components/kbd" },
  { title: "Label", url: "/components/label" },
  { title: "Lucide Icons", url: "/components/lucide-icons" },
  { title: "Menubar", url: "/components/menubar" },
  { title: "Native Select", url: "/components/native-select" },
  { title: "Navigation Menu", url: "/components/navigation-menu" },
  { title: "Pagination", url: "/components/pagination" },
  { title: "Popover", url: "/components/popover" },
  { title: "Progress", url: "/components/progress" },
  { title: "Radio Group", url: "/components/radio-group" },
  { title: "Resizable", url: "/components/resizable" },
  { title: "Scroll Area", url: "/components/scroll-area" },
  { title: "Select", url: "/components/select" },
  { title: "Separator", url: "/components/separator" },
  { title: "Sheet", url: "/components/sheet" },
  { title: "Sidebar", url: "/components/sidebar" },
  { title: "Skeleton", url: "/components/skeleton" },
  { title: "Slider", url: "/components/slider" },
  { title: "Spinner", url: "/components/spinner" },
  { title: "Switch", url: "/components/switch" },
  { title: "Table", url: "/components/table" },
  { title: "Tabs", url: "/components/tabs" },
  { title: "Textarea", url: "/components/textarea" },
  { title: "Toast", url: "/components/toast" },
  { title: "Toggle", url: "/components/toggle" },
  { title: "Toggle Group", url: "/components/toggle-group" },
  { title: "Tooltip", url: "/components/tooltip" },
  { title: "Typography", url: "/components/typography" },
]

export const mainNavigation = [
  {
    title: "Dashboard",
    url: "/",
    icon: "Home",
  },
  {
    title: "Analytics", 
    url: "#",
    icon: "BarChart3",
  },
  {
    title: "Projects",
    url: "#",
    icon: "Folder",
  },
  {
    title: "Team",
    url: "#",
    icon: "Users",
  },
  {
    title: "Settings",
    url: "#",
    icon: "Settings",
  },
]

export const widgetsNavigation = {
  title: "Widgets",
  url: "/dashboard/widgets",
  icon: "Proportions"
}
